### ISSUE TITLE
Add a secret.json for exemple

### ISSUE THREAD

**Issue by FuryCraft** [FalixInc/FalixCoins-Miner#5]
Please, would it be possible to add a secret file.json file! I find it very interesting how you trim Falixcies with this minor, I suggest that the secret file.json indicates the secret key of dashactyl but could you still add it?

**Comment by flaxeneel2** [comment]
Hi there! 

The miner does not hook directly into dashdactyl, instead, there is a custom made API which handles the requests. As for the contents of the secret.json, it does not include anything fancy, it just contains a value "a" (authentication) and "u" (url). As the names would suggest, the "a" is the auth key, authenticating the request, and "u" is the url it is posting to. There is nothing truly worthwhile in the secrets.json so I deemed it being better to not upload it at all (to prevent accidental url and auth key leaks while committing).

Regards,
Flaxeneel2
